version: "3.7"

services:
  app:
    build: .
    ports:
      - "5000:80"
    depends_on:
      - db
    environment:
      DB_SQL_SERVER_EXPRESS: "Server=db;Database=master;User=sa;Password=Your_password123"
  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    ports:
      - "1434:1433"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"